services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # лечим нулпоинтер
      KAFKA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:-UseContainerSupport"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # лечим нулпоинтер
      KAFKA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:-UseContainerSupport"
    volumes:
      - ./kafka-data:/var/lib/kafka/data

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  web:
    build: ./api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - clickhouse
      - kafka
    volumes:
      - ./:/api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_PASSWORD=123456

  cron_job:
    build: ./cron_job
    container_name: cron_job
    ports:
      - "9999:9999"
    depends_on:
      - postgres
      - clickhouse
      - kafka
    volumes:
      - ./:/cron_job
volumes:
  postgres_data:
  clickhouse_data: